/*
    1. this script is created for SETUP purposes only, it creates schema from scratch and inserts all possible data
    2. it is very inaccurate to use it in case of data update
    3. use it only when migrating, replicating or creating schema from scratch

    In compliance with its destiny, running this script on the database which contains actual schema will result in an error :)
*/

/*
    Most of the fields are set to default null, it comes from the structure of our data,
        it is very messy so any serious constraints my cause a disaster
*/

/*
    MEDIUMINT - enough for the job, SMALLINT is too small (32k is the limit)

    FLOAT without defined precion as FLOAT(M, D) -
        because precision is deprecated and FLOAT is enough four our values

    TEXT - 65,5.. k characters is quite much but the previous tier is 255 chars so it is a must in this case
        even though it is redundant
*/
START TRANSACTION;

CREATE TABLE teacher(
                        teacherId MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
                        category VARCHAR(30) NOT NULL,
                        full_name VARCHAR(80) DEFAULT NULL,
                        academic_title VARCHAR(30) DEFAULT NULL,
                        average_rating FLOAT,
                        details_link VARCHAR(50) NOT NULL
);

CREATE TABLE review(
                       reviewId MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
                       course_name VARCHAR(60) DEFAULT NULL,
                       given_rating FLOAT,
                       title VARCHAR(100) DEFAULT NULL,
                       review TEXT DEFAULT NULL,
                       reviewer VARCHAR(30) DEFAULT NULL,
                       post_date DATETIME,
                       teacher_id MEDIUMINT NOT NULL,
                       FOREIGN KEY (teacher_id) REFERENCES teacher(teacherId)
);

INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Rańda Paweł', 'mgr', 4.71, 't,randa-pawel-mgr,24324');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.0, '', 'Wioślarstwo Polecam! Zajęcia odbywały się dosyć daleko, ale było warto. Super atmosfera z doświadczonym sportowcem. Pan Paweł bardzo dobrze wytłumaczył i pokazał jak wykonywać dane ćwiczenia. Zaliczenie za obecności. Można dwa razy nie być i to nie wpływa na ocenę. Zajęcia dosyć męczące ale chyba o to w tym chodzi. Bardzo polecam', 'Anonymous', '2014-09-14 17:18', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo', 5.0, 'ocena opisowa - POLECAM ! ! !', 'Zapisałem się na zajęcia w semestrze zimowym z nadzieją, że uda się choć raz wyjść na wodę. Kiedy na pierwszym spotkaniu okazało się, że jednak tylko ergometr, to lekko się załamałem. Myślałem, że będzie nudno, długo i do czterech liter. Nie mogłem się jednak bardziej mylić. Prowadzący ma dużą wiedzę na temat tego sportu. Treningi są ciężkie i męczące, ale przynosiły mi dużą satysfakcję. Choć były to tylko maszyny, to prowadzący układał treningi tak, że za każdy razem było inaczej, przez co ciekawie. Po tych zajęciach moja ochota do wiosłowania tak się zwiększyła, że będę starał wepchnąć się do sekcji. Polecam zajęcia z Panem Rańdą pod każdym względem.', 'Waga opinii: x1,06', '2014-02-03 00:37', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo', 3.0, 'ocena opisowa - ee żal', 'Pierwsze zajęcia sprawiły, że wioślarstwo to coś czego szukałem od zawsze. Niestety z zajęc na zajecia, moj zapał gasł. Prowadzącego więcej nie było niż był. Czasem robił fajne cwiczenia, czasem tylko wyznaczył ilość kilometrow, kto skonczyl to do domu. Inny prowadzacy poszedl na wode, my ani razu w semestrze letnim. Troche mu sie nie chce. Jako tako do powioslowania moze byc. Zapewne na sekcji przyklada sie 100%. No tutaj tylko zwykly wf to olewa.', 'Waga opinii: x1,05', '2014-06-15 19:34', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.0, '', 'Wioślarstwo Polecam! Zajęcia odbywały się dosyć daleko, ale było warto. Super atmosfera z doświadczonym sportowcem. Pan Paweł bardzo dobrze wytłumaczył i pokazał jak wykonywać dane ćwiczenia. Zaliczenie za obecności. Można dwa razy nie być i to nie wpływa na ocenę. Zajęcia dosyć męczące ale chyba o to w tym chodzi. Bardzo polecam', 'Anonymous', '2014-09-14 17:18', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.0, 'polecam, OK!', 'Prowadzący często nie obecny ponieważ dostał się do rady miasta i ma jakieś spotkania. Zajęcia odbywały się zawsze co najwyżej zastępstwo było. Bardzo w porządku do studentów, jak ktoś nie wie jak ćwiczyć to pokazuje ćwiczenia.', 'Anonymous', '2015-02-04 11:39', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo', 5.5, 'ocena opisowa - Świetny człowiek', 'Nigdy wcześniej nie miałem do czynienia z wioślarstwem, szczerze zapisałem się tam tylko dlatego że odpowiadały mi godziny zajęć. Jednak dzięki niemu zakochałem się w tym sporcie! Bardzo przykładał się do techniki w jaki wykonywaliśmy ćwiczenia. Zajęcia nie były nudne, prowadzone w interesujący sposób. Jeżeli lubisz się porządnie wymęczyć to lepiej trafić nie możesz!', 'Anonymous', '2015-02-12 23:53', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo', 4.5, 'poleam', 'Ocena za obecność. Prowadzący lubi się czasami nie pojawić na zajęciach, ale wtedy zawsze zastępstwo. Na samych zajęciach rozgrzewga i później ergonometry. Czasami rozgrzewka jest już na ergonometrach. Szczerze poelcam tego prowadzącego', 'Anonymous', '2015-05-14 10:22', 1);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo', 5.0, 'na luzie', 'Ćwiczenia odbywały się na ergometrach, za każdym razem z sali wracałem wykończony, czyli swoją rolę spełniały. Warto dodać, że nie odbywało się to na zasadzie "zróbcie 5 km i narka", tylko były bardzo często wprowadzane modyfikacje, zabawy, rywalizacja w grupach itd. Mogę powiedzieć, że po prostu dobrze się bawiłem na tych zajęciach.', 'Waga opinii: x1', '2019-01-13 16:48', 1);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Stasiak Przemysław', 'mgr', 5.0, 't,stasiak-przemyslaw-mgr,2126');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Płetwonurkowanie', 5.0, 'POLECAM !', 'Na początku test. 10 minut na wodzie w pozycji pionowej lub 2 minuty w tej samej pozycji z rękami w górze. Oczywiście poszedłem pod wodę, bo to było pierwsze wejście do wody po 3 latach ;D Nie poddałem się i warto było. Zajęcia są super. Poprawiły moją kondycję, siłę, a także sposób podejścia do wody. Na rozgrzewkę było zawsze 20 basenów. Pan Stasiak umie wszystko wytłumaczyć i ma dość specyficzne poczucie humoru, które bardzo mi się podobało. Poza pływaniem w sprzęcie ABC zorganizował nam zajęcia w pełnym sprzęcie (butla, kamizelka BCD), a także holowanie, ćwiczenia z podręcznika... jakiego dowiecie się na kursie i wiele wiele innych rzeczy. Jedno mogę powiedzieć. Uważałem, że radzę sobie w wodzie. Ten kurs uświadomił mi jak bardzo się myliłem. Jeśli chcecie prawdziwego wf-u, a nie jakiegoś obijania się paletkami to polecam ten kurs.', '', '2007-02-19 21:24', 2);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Stefanowski Dariusz', 'mgr', 4.38, 't,stefanowski-dariusz-mgr,29376');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Zdalne pływanko', 3.5, 'Psychicznie sie bardziej zmęczyłam niż fizycznie', 'Tragedia, na początku do wykonania zadania tekstowe i odesłanie ich mailem, wyjątkowo kuriozalne było obliczenie swojego CPM i sporządzenia jadłospisu uwzględniając makroskładniki... To chyba nie ten typ uczelni. Ćwiczyć trzeba było (do wyboru) : na kamerkach lub nagrywając się i przesyłając materiał prowadzącemu. Jak sam mówi preferuje sposób pierwszy, bo w innym przypadku musi nas potem oglądać. Na szczęście sumarycznie wyszło ok 5-10 minut "pocenia się", a potem przeczekanie do końca zajęć. Prowadzący RAZ (na ostatnich zajęciach) pokazał nam jakoby od niechcenia jak wykonać ćwiczenie. Nie do końca chyba też wiedział że na Teamsie widać było max 9 osób, przez co część ćwiczących i tak dostawała dopisek "brak kamery" po zajęciach. Na plus - można mieć 4 nieobecności. Ogólnie nie polecam.', 'Anonymous', '2021-02-18 22:23', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy - C', 4.0, 'OK ale uciążliwe zaliczenie', 'Po zdalnym WF-ie nie można się wiele spodziewać Prowadzący dobrze przygotowany do zajęć jednak wysyłanie co tydzień 10 minutowych filmików z własnych ćwiczeń jest uciążliwe. Jest możliwość ćwiczenia przy włączonych kamerkach ale mimo wszystko można zaliczyć ten kurs dużo łatwiej.', 'Anonymous', '2021-02-05 18:11', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie - C', 4.0, '(wf-zdalny) - nic specjalnego', 'Co tydzień godzinne spotkanie, podczas którego były różne tematy np. zdrowe plecy i inne mało ciekawe. Często oprócz samych ćwiczeń na kamerce lub nagrywanych i następnie wysyłanych do niego(ok. 10 min), należało robić prace pisemne podczas zajęć np. na podstawie artykułów wypisać choroby związane z otyłością. Ogólnie jak tłumaczy co należy robić, to wydaje się jakby robił to za karę. Nie ocenia systematycznie żadnych prac, tylko na koniec wystawia ocenę za ogół. Na pewno bardzo ważne są obecności. Na zajęcia zdalne raczej nie polecam, słyszałem lepsze opinie o innych prowadzących.', 'Anonymous', '2021-02-16 16:33', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('wioślarstwo', 5.0, 'ocena opisowa - super', 'Niestety w moim przypadku były to zajęcia zdalne. Polegały one głównie na zrobieniu kilku zadań teoretycznych (odpowiadanie na pytania typu co to jest trening funkcjonalny) lub praktycznych. Na każdych zajęciach trzeba zrobić rozgrzewkę/wyznaczony zestaw ćwiczeń na kamerce lub wysłać nagranie jak ćwiczymy ok.10min to trwa. Później można wyłączyć kamerkę i ćwiczyć serie we własnym zakresie. Ciekawe i luźne zajęcia sportowe jak na to że były w trybie zdalnym.', 'Anonymous', '2021-02-18 12:47', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('zdalny WF wioślarstwo', 5.0, 'Bezproblemowo', 'Na początku każdych zajęć było do zrobienia kilka zadań tekstowych(zadania były zawiązane z przerabianymi ćwiczeniami np. opracować własny zestaw ćwiczeń lub wyszukać jakiś definicji w internecie itp. ), które należało przesłać do prowadzącego po zajęciach. W drugiej części zajęć wykonywało się serię ćwiczeń podanych przez prowadzącego na włączonej kamerce lub należało przesłać nagranie jak wykonuję się te ćwiczenia.', 'Anonymous', '2021-02-18 13:45', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Zdalne pływanko', 3.5, 'Psychicznie sie bardziej zmęczyłam niż fizycznie', 'Tragedia, na początku do wykonania zadania tekstowe i odesłanie ich mailem, wyjątkowo kuriozalne było obliczenie swojego CPM i sporządzenia jadłospisu uwzględniając makroskładniki... To chyba nie ten typ uczelni. Ćwiczyć trzeba było (do wyboru) : na kamerkach lub nagrywając się i przesyłając materiał prowadzącemu. Jak sam mówi preferuje sposób pierwszy, bo w innym przypadku musi nas potem oglądać. Na szczęście sumarycznie wyszło ok 5-10 minut "pocenia się", a potem przeczekanie do końca zajęć. Prowadzący RAZ (na ostatnich zajęciach) pokazał nam jakoby od niechcenia jak wykonać ćwiczenie. Nie do końca chyba też wiedział że na Teamsie widać było max 9 osób, przez co część ćwiczących i tak dostawała dopisek "brak kamery" po zajęciach. Na plus - można mieć 4 nieobecności. Ogólnie nie polecam.', 'Anonymous', '2021-02-18 22:23', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie', 4.5, 'w porządku', 'Pływanie zdalne - no jak można się spodziewać w wannie się nie kąpiemy Zaliczenie chyba na każdym WF takie samo - nagrywanie jak się ćwiczy i jakieś tam zadanka z kwestii sportowych. Ogółem mgr Stefanowski nie utrudniał nam życia, większość grupy dostała 5. Także polecam:) Ale co do nagrań/zadań był skrupulatny.', 'Anonymous', '2021-07-06 10:09', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 4.0, '', '[b]Kurs: trening funkcjonalny [b]Ocena opisowa: dobry Mało wymagający prowadzący. Uczestniczyłem na zajęciach zdalnych, wystarczyło wchodzić na spotkania, w przypadku nie wysłania filmów z ćwiczeniami nic się nie działo. Nie wiem jak wyglądają zajęcia stacjonarnie, na zdalne polecam.', 'Anonymous', '2021-09-05 16:33', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Trening funkcjonalny [zdalnie]', 3.5, 'Nieciekawie', 'Prowadzący czytał jakieś teksty z kartki w usypiający sposób i ani razu nie ruszył się na zajęciach. Rozumiem, że prowadzenie zajęć sportowych zdalnie to nic łatwego ani fajnego, ale innym prowadzącym (z którymi miałem styczność) wychodziło to lepiej.', 'Anonymous', '2021-09-22 11:33', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie [stacjonarne/zdalne]', 5.0, 'ocena opisowa - Super zajęcia', 'Przez stacjonarną część semestru zajęcia wyglądały tak, że wystarczyło przyjść odhaczyć obecność, a następnie każdy miał dowolność w tym ile basenów danego dnia ma ochotę przepłynąć. Zaliczenie na podstawie liczby obecności. Jedna nieobecność jest ,,darmowa\'\' za każdą następną końcowa ocena jest obniżana o pół stopnia. Jeżeli ktoś umie pływać to może na tych zajęciach od własnego uznania albo się zrelaksować, albo faktycznie dużo popływać.', 'Anonymous', '2022-02-14 17:47', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie zdalne/stacjonarne', 4.5, 'Dobry wybór', 'Na zajęciach stacjonarnych prowadzący tylko raz narzucił nam jakieś ćwiczenia a tak to wolna ręka. nie zwracał za bardzo na nas uwagi więc można było sobie i popływać i pogadać. Na zdalnych wymagane ćwiczenia na kamerce. ja wysłałem 2-3 nagrania i mam 4 chociaż powinienem mieć 3. Na minus że pomimo nie ćwiczenia na spotkaniu prowadzący oczekiwał obecności co jest trochę bezsensu ponieważ i tak ćwiczenia wykonywałem później.', 'Anonymous', '2022-02-15 07:04', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Wioślarstwo 30h', 5.0, 'Kochany i cierpliwy', 'Sposób prowadzenia zajęć: Zrównoważony Czy potrafi nauczyć? Tak Podstawa oceny w indeksie / zaliczenia: Wykonywanie zajęć w miarę możliwości. Niespodziewajki: Zdecydowanie brak. Poczucie humoru: Poważny. Ogólne podejście do studenta: Bardzo sprawiedliwy i cierpliwy. Ocena ogólna: Jeden z najbardziej niezawodnych prowadzących. Polecam serdecznie!', 'Anonymous', '2022-02-18 20:22', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie', 4.5, 'Polecam', 'Nie robi problemu z zaliczeniem. Zdalne pływanie nie oddaje, lecz stacjonarnie było przyjemnie. Pokazał podstawy, każdy w swoim tempie pływał w różnych stylach. Nie wymaga zbyt wiele na zdalnych, 15 minut ćwiczeń wysłanych na pocztę lub na kamerce. Ogółem w porządku dla studentów.', 'Anonymous', '2022-02-18 22:03', 3);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Nauka pływania (Ćw)', 4.5, '', 'Oena opisowa: ogółem do polecenia Prowadzący bardzo w porządku. Nie robi problemów z zaliczeniem. Stacjonarnie szło się czasem trochę zmęczyć różnymi ćwiczeniami ale każdy i tak tempo dostosowywał do siebie. Zdalnie trzeba było ćwiczyć kilkanaście minut na kamerce albo nagrać ćwiczenia, które umieszczał na teamsach. Czasem zdarzało mu się nie przyjść na zdalne, ale zaliczał obecność.', 'Anonymous', '2022-02-21 16:09', 3);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Szemraj', '', 2.5, 't,szemraj,2447');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 2.0, 'praca praca praca !!:)', 'Typ wyrwany ze starego systemu, non stop nawija o tym jak to trza ciężko pracować itd itp, w połączeniu z jego wyglądem robi się śmiesznie ale tylko do czasu. Nie pozwala usiąść choćby na chwile i korzystająć z "systemu" luster inwigiluje i pogania:) Dobra było śmiesznie teraz do rzeczy. Miałem zaj. o 7:30 (kulturystyke!!!!) to tak jakby ktos kazał ci w łóżku albo na kacu dźwigać cieżary, obłęd. Margines na spóźnienie = 0 bo gość zamyka drzwi, ja spóźniłem sie ze 3 razy (dosłownie 2, 3 min! ) to mi podziękował i oblał nie biorąc przy tym pod uwagę wyników z zaliczeń próbnych (na marginesie na 5). Podobno nie powinniśmy tu nikogo obrażać ale dla mnie ten facet to zwykły (ocenzurowano)!', 'Waga opinii: x1,17 opinia wyróżniona', '2007-04-03 11:01', 4);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 3.0, '', 'Samoobrona Ciężko, ciężko Każdego ocenia pod swoim kątem stąd brak zrozumienia dla osoby, która przecież może być np. zmęczona. Polecam tylko naprawde wytrwałym. Mam nienajlepsze wspomnienia. Fikołki przez całą sale będę pamiętać do końca życia.', '', '2007-10-12 09:13', 4);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Śliwiński Jerzy', 'mgr', 5.12, 't,sliwinski-jerzy-mgr,94');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.5, 'Idealne zajęcia sportowe', 'Prowadzący (razem z mgr Krzysztofem Niewiarą) prowadził zajęcia sportowe zwane turystyką górską. Były to 3 wyjazdy: 1 jednodniowy oraz 2 dwudniowe. System oceniania jakiś tam był, ale jeżeli było się na wszystkich wyjazdach było 5. Jak się na jakimś nie było, to można było odrabiać żeby podnieść ocenę/zaliczyć. Prowadzący nie przejmowali się za bardzo grupą (zamykali szlak idąc na końcu, więc była to gwarancja braku maruderów). Dużo tu nie ma co mówić - po prostu polecam!', 'Anonymous', '2017-01-28 14:09', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.5, '', 'Ma przyjazny stosunek do studenta zajęcia są dobrze prowadzone. Ocena jest za obecność. Polecam.', '', '2006-02-16 11:14', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.0, 'Polecam', 'Świetny człowiek, naprawdę bardzo przyjazny dla studentów. Jak w każdym WF liczy się obecność, ale nie ma problemów żeby na koniec załapać 5.0 Lubi żartować, widać że praca sprawia mu przyjemność.', '', '2006-02-17 15:45', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('futsal', 5.0, '', 'rowniez jak najbardziej polecam, swietny sympatyczny facet. zajecia sa ciekawie prowadzone i jeszcze pewnie sie kiedys do niego zapisze ;]', '', '2006-02-17 16:07', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pilka Nozna', 4.5, '', 'Za obecnosc 5.0 (mozliwosc odrobek nieobecnosci) Mialem z tym panem 1 kurs i teraz zapisalem sie jeszcze raz. Bardzo milo go wspominam. Luzne zajecia, choc na pierwszych dosyc duzo mielismy cwiczen z pilkami i bez zanim zaczelismy grac i troche to bylo meczace... ale juz od polowy semestru rozgrzewka trwala chwile i po niej gralismy w pile. POLECAM', '', '2006-03-08 17:22', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 4.5, '', 'kurs : piłka nożna gość ogólnie w porządku, szkoda tylko ze na 1.5 godziny zajeć rozgrzewka zajmowala od 30 do 40 minut', '', '2006-06-26 08:12', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.5, 'Polecam', 'Bardzo dobry i przyjazny stosunek do studenta.Ocena na podstawie obecności , za wszystkie 5.0.W przypadku jednej nieobecności ocena w dół itd.Zajęciaprowadzone w miły sposób , raz nawet ubrał plastron i zami zagrał co mu się chyba nie zdarza.Bardzo miłe zajęcia.', '', '2006-09-30 17:48', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.0, 'ocena opisowa - polecam', 'Extra zajęcia, mozna odrabiac do przodu bez konsekwencji, zajecia to z reguły 30 minut rozgrzewki [troche biegania, stretching, zabawa z piłkami] + godzina gierki. fajnie', 'Waga opinii: x1,01', '2006-10-03 21:50', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Łyżwiarstwo', 5.0, 'ocena opisowa - polecam', 'naprawdę w porządku Gość, zajęcia zabawne, zaliczenia za obecność', '', '2007-01-18 20:07', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('koszykówka', 5.0, 'ocena opisowa: ok!', 'Bez problemu. Jeden z najbardziej niekonfliktowych ludzi w SWFiS. Zajęcia w normie - ani źle, ani dobrze (jego konikiem jest piłka nożna, stąd pewnie na koszykówce "tylko" standard). Miły, uprzejmy, sympatyczny, nie robi problemów z zaliczeniem. Zasłużony pozytyw.', 'Waga opinii: x1,05', '2007-02-12 18:01', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.5, '', 'Ocena: 5,5 Kurs: futsal ocena opisowa: Jest w porządku,warto sie zapisac!!POLECAM!', '', '2007-02-14 20:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.5, 'POLECAM', 'Fajny człowieczek z dobrym poczuciem humoru. Wystarczy przychodzić na zajęcia bo to obecność na nich jest wyznacznikiem oceny końcowej. Prowadzący ma konkretny sposób prowadzenia zajęć dzięki czemu każdy sie na pewno zmęczy i porządnie spoci', '', '2007-10-15 11:56', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('piłka nożna', 5.5, 'ocena opisowa - jak najbardziej OK', 'Zajecia wygladaly w nastepujacy sposob: 15-20 min rozgrzewki a potem gralismy do konca Ocena byla wystawiona za obecosci, z odrabianiem ich nie byla najmniejszego problemu.', 'Waga opinii: x1,07', '2008-01-27 15:47', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'Super!!!', 'Facet bardzo wyluzowany z poczuciem humoru.Zajecia prowadzone ciekawie, często daje przydatne wskazówki i ćwiczy niektóre zagrania indywidualnie jeśli coś Ci nie wychodzi to przydatna informacja dla tych, którzy nigdy nie grali w tenisa lub dopiero zaczynają;) Zaliczenie na obecność. Lepiej też sie nie spóźniać bo sumuje ile czasu się spóźniłeś i jeśli przekroczy 1,5 to dochodzi jedna nieobecność. POLECAM!!', '', '2008-02-15 15:18', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('tenis', 5.0, 'ocena opisowa -', 'jest najlepszy :) Naprawde chce sie chodzić na zajecia... nawet jeśli są na 7:30', '', '2008-02-23 14:42', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'ocena opisowa - polecam', 'Jasne zasady, bez marudzeń, rozgrzewka z zajęć na zajęcia coraz mniej wymęczająca. Jedynym mankamentem mgr\'a jest to, że nie istnieje dla niego ocena 4,5 Jak ma się wszystkie obecności ma się 5, jedna nieobecność - 4, dwie 3,5 itd. Zajęcia można odrabiać na prowadzonej tez przez niego halówce i piłce nożnej. Polecam', '', '2009-02-20 19:18', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('piłka nożna/halowa/futsal', 5.5, 'ocena opisowa - brać w ciemno', 'Wyrobiłem u tego pana 4 semestry piłki nożnej pod różnymi postaciami i powiem tyle - super. Na początek rozgrzewka, a raczej nauka jak ja prowadzic w przyszlosci. Na koniec zajec kazdy juz wie jak to powinno wygladac. Potem standardowo mecz, bez wslizgow, ostrej gry. Za brutalne zagranie mozna wyleciec z zajec. Odrabiasz na czym chcesz i kiedy chcesz, byle byly to zajecia u mgra Sliwinskiego (jezeli laczna liczba osob nie jest wieksza niz 20, wtedy pierszenstwo maja Ci zapisani na dana godzine, a reszta losuje miedzy soba, kto zostaje odrabiac). Ogolnie zawsze sa miejsca w piatek na 15.30, wiec polecam ta godzine jesli chodzi o odrobki. Reasumujac - rewelacja jak na warunki politechniczne.', 'Waga opinii: x1,02', '2009-07-04 23:44', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka Nożna', 5.0, 'Spoko loko', 'Wszystko tak jak piszą poprzednicy. Dodam tylko, że jedyną wadą jest niższa ocena za nieodrobione zajęcia. Polecam.', '', '2010-01-22 23:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna halowa', 5.0, 'ocena opisowa - polecam', 'Na początek zajęć rozgrzewka ok. 10 minutowa, potem podział na druzyny i jazda Można odrabiać zajęcia, wszystkie obecności = 5 w indeksie', '', '2010-02-06 10:18', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.0, 'Polecam', 'Naprawdę dobry prowadzący, z poczuciem humoru. Na każdych zajęciach jakiś turniej, którego zwycięzca dostaje jedną obecność w wybranym przez siebie terminie gratis Czasami jak widzi, że ktoś robi coś źle, podejdzie i pokaże, jak powinno się dane zagranie wykonać. Warto się zapisać.', '', '2010-02-19 14:25', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.0, '', '', 'Waga opinii: x1,01', '2010-02-20 18:01', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('tenis ziemny', 5.5, '', 'Świetny prowadzący, ma pozytywne podejście do studenta i prowadzenia zajęć, widać że chce i potrafi nauczyć gry w tenisa. Na pierwszych zajęciach dzieli ludzi (hala GEM) na podstawie jednego zagrania back i forhand na zaawansowanych, średnio i początkujących. Tym ostatnim daje na początku zawsze jakieś ćwiczenia, a pod koniec granie, średni troche ćwiczeń, a zaaw. grają do woli. Trzeba mieć swoją rakietę, na pierwszych zajęciach niektórzy kupowali tam na miejscu, na hali. Piłki w tym semestrze ufundowała nam politechnika Nie trzeba umieć grać żeby brać udział w tych zajęciach, trener daje liczne proste ćwiczenia takim, typu odbijanie for/backhand, serwowanie itp. oraz sporo cennych wskazówek Ocena za obecność - żadnych nieobecności = 5.0 w indeksie POLECAM!', '', '2011-02-02 19:39', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('turystyka górska mgr Śliwiński, mgr Niewiara', 5.0, 'ocena opisowa - Polecam', 'Polecam turystykę górską u tych prowadzących, trasy nie są zbyt męczące, jeżeli ktoś nie daje rady to prowadzący dostosowują do niego tempo, mgr Śliwiński oraz mgr Niewiara zachowują się neutralnie, ogólnie mówiąc nie wtrącają się w wycieczki, masz wrażenie jakby go w cale ich niebyło.', 'Waga opinii: x1,03', '2011-02-07 16:04', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska - Karkonosze, J. Śliwiński, K. Niewiara', 5.5, 'ocena opisowa - Super', 'Super zajęcia z tymi prowadzącymi. Dwa wyjazdy weekendowe w Karkonosze, jeden na Ślęże. Wycieczki o różnym stopniu trudności. W soboty trudniejsze, w niedzielę krótsze - udział we wszystkich 5. Ekstra atmosfera, a gadanie o bibach między bajki włożyć. Prowadzący są konkretni, wyjścia punktualnie o zapowiedzianej porze, trasy dostosowane do pogody, czas po wycieczkach jest wolny. Polecam.', '', '2011-02-28 18:38', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska - Tatry, J. Śliwiński, K. Niewiara', 5.0, 'ocena opisowa - 5,0', '', 'Waga opinii: x1,14', '2011-10-28 12:03', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('piłka nożna halowa/tenis stołowy', 5.0, '', 'Za wszystkie obecności na zajęciach jest 5.0 w indeksie. Zajęcia można odrabiać na innych prowadzonych przez Pana Śliwińskiego bądź też u innych sportowców jeśli wyrażą zgodę. Można też bez problemu odrobić dowolną ilość awansem. Piłka nożna halowa: mimo nieciekawej hali na Niskich Łąkach zajęcia są świetne dla tych co lubią pograć w nogę - nie polecam jak ktoś chce mieć z głowy wf. Tenis stołowy: Nie trzeba się przemęczać, jednak za kompletny brak zaangażowania można być wywalonym z zajęć (szczególnie na odróbkach ).', '', '2012-02-06 11:32', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.5, 'Idealne zajęcia sportowe', 'Prowadzący (razem z mgr Krzysztofem Niewiarą) prowadził zajęcia sportowe zwane turystyką górską. Były to 3 wyjazdy: 1 jednodniowy oraz 2 dwudniowe. System oceniania jakiś tam był, ale jeżeli było się na wszystkich wyjazdach było 5. Jak się na jakimś nie było, to można było odrabiać żeby podnieść ocenę/zaliczyć. Prowadzący nie przejmowali się za bardzo grupą (zamykali szlak idąc na końcu, więc była to gwarancja braku maruderów). Dużo tu nie ma co mówić - po prostu polecam!', 'Anonymous', '2017-01-28 14:09', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.5, 'Zdecydowanie polecam!', 'Zdecydowanie polecam kurs z tym Panem. Śmiało można się zapisywać. Zajęcia prowadzone bezstresowo, jednak trzeba chodzić na zajęcia. Każda nieobecność, to pół oceny w dół.', '', '2012-02-06 19:04', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('tenis stołowy', 5.5, 'ocena opisowa - super!', 'naprawdę dobre warunki jeśli chodzi o odróbki - niby można mieć 3 w semestrze, ale w praktyce wychodzi tak, że można odrabiać ile się chce przychodząc na inne zajęcia Pana Śliwińskiego, wtedy odznacza od razu obecnośc na karcie i już dodatkowo czas na odróbkę nie jest ograniczony jak to zazwyczaj bywa 2 tygodnie, tylko o ocenę można walczyć do ostatniego dnia semestru. Można też zrobić dowolną ilość zajęć z wyprzedzeniem (chodząc na wf innej grupy prowadzonej przez Pana), wtedy dostaje się wpis szybciej. Prowadzący jest bardzo sympatyczny. Pozwalał odrabiać nieobecności także osobom z innych sportów, ale trzeba wykazać chociaż minimum aktywności bo podpierania ścian nie lubi i przy takiej odróbce potrafi wyrzucić z zajęć', '', '2012-02-09 21:11', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 4.5, 'ocena opisowa:', 'Piłka nożna  polecam Dobrze prowadzone zajęcia, solidna rozgrzewka, potem sędziowana gra. Jedna połowa semestru na sztucznej nawierzchni na dworze, druga na sztucznej trawie w hali. Przyjazny, sympatyczny, pozwala na odrabianie zajęć z drugą grupą lub na siłowni.', '', '2012-02-10 12:39', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.0, 'Prowadzący godny polecenia', 'Zaliczenia na podstawie obecności. Pierwsze rozgrzewki dają trochę w kość, później jest lepiej. Zaczyna się zawsze od elementów technicznych - przyjęcie, podanie, różne warianty. Bez problemu można odrabiać nieobecności wtedy ocena nie schodzi w dół. Polecam!', 'Anonymous', '2012-02-10 14:53', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.5, '', 'Kurs: Piłka nożna Polecam Tak jak napisali poprzednicy, potwierdzam, że warto systematycznie uczęszczać na zajęcia, które są naprawdę pasjonujące. Dla mnie to była prawdziwa przyjemność i odskocznia od codziennych stresów. Dzięki Prowadzącemu zajęcia poprawiłem i udoskonaliłem własną technikę gry, z czego jestem dumny. Naprawdę warto być na zajęciach u tego Pana. Polecam', 'Waga opinii: x1,05', '2012-02-10 19:20', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka Siatkowa', 5.0, 'ocena opisowa - w porządalu', 'Pan Śliwiński nie sprawiał absolutnie żadnych problemów, jak ktoś lubi siatkówkę to przychodził na zajęcia po prostu odpocząć, pograć sobie i tak te zajęcia właśnie wyglądały. Zaliczenie oczywiście za obecności, początkowo drobne problemy z odrobieniem zaległych zajęć ("bo ja mam grupę zaawansowaną jeszcze, ale pan się nie nadaje to ja nie wiem..") ale w końcu zaprosił na odróbkę i jest piąteczka w indeksie Polecam.', '', '2012-02-11 11:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis Stołowy', 5.0, 'ocena opisowa - Jak najbardziej na tak!', 'Prowadzący jak najbardziej w porządku. Nie było jakichkolwiek problemów z zaliczaniem, a jeśli ktoś chciał się nauczyć grać, a nie szło mu dość dobrze, Pan Jerzy potrafił wyłapać takich osobników i wspomóc ich radą.', 'Anonymous', '2012-05-30 15:18', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('piłka nożna i futsal', 5.5, 'Jeśli są miejsca to wbijać drzwiami i oknami@', 'Świetny trener, zawsze na początku porządna rozgrzewka (która na początku semestru strasznie doskwierała rozleniwionym studentom i autentycznie brakowało siły na grę ), raz na jakiś czas gra sprawnościowa, później sama gra. Czasami robi turnieje gdzie zwycięskie drużyny zyskują jedną obecność Ogólnie bardzo ugodowy facet, jeśli tylko są miejsca to pozwala odrabiać na zajęciach innych grup (można odrabiać futsal na nożnej i vice versa). Jak ktoś się uprze to w ten sposób można zrobić cały semestr w kilka tygodni. Nie toleruje spóźnień. Wyzywa od reprezentacji Polski jeśli ktoś daje popis drewnianej gry Chamstwa i wymachiwania rękami w swoją stronę nie znosi i daje żółte kartki (0.5 oceny w dół ) Raz się zdarzyło w futsalu że wyrzucił młokosa z czerwoną kartką (1 ocena w dół + nieobecność) ale chłopaczek się prosił. Jak pisałem wyżej - gorąco polecam tego pana.', 'Anonymous', '2012-05-31 22:23', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis Stołowy', 5.0, 'ocena opisowa - Polecam!', 'Zajęcia prowadzone w sposób przyjemny. Lekka rozgrzewka, chwila gry treningowej i w większości przypadków turniej, w którym można wygrać obecność. Ocena jest uzależniona od obecności - brak jednej to 1 ocena w dół, ale z odrabianiem nie ma problemów (no chyba że pod koniec semestru).', '', '2012-09-17 10:25', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Squash', 5.0, 'polecam', 'Świetny prowadzący z przyjaznym stosunkiem do studenta. Bardzo ważne są obecności (to akurat traktuje naprawdę serio - zwolnienia lekarskie nie są respektowane), ale można odrabiać zaległości. Po semestrze squasha z tym Panem można już powiedzieć, że potrafi się zagrać mecz . Fajnie się ogląda jak czasem gra z innym studentem - student lata za piłką, a on sobie spokojnie odbija, czasem robiąc klika kroków', '', '2013-01-26 20:01', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.5, '', 'Ocena: 5,5 Kurs: Tenis ziemny Ekstra gość, polecam !!! Facet z poczuciem humoru i bardzo wyluzowany jedna rzecz jaka się dla niego liczy to obecności i spóźnienia. Jeśli nie grałeś nigdy w tenisa to wal do niego bez problemu. Na samym początku dzieli osoby na 2 grupy tych co już coś tam kiedyś grali i tych co zaczynają. Potrafi z niektórymi osobami spędzić nawet 20 min próbując dobrze nauczyć zagrania.', '', '2013-02-01 17:58', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'ocena opisowa - Polecam', 'Dobry prowadzący, tych którzy potrafią grać w tenisa nie przeszkadza, a tym którzy chcą się nauczyć pomaga. Wystarczy mieć obecności na 5 na koniec', 'Anonymous', '2013-02-03 10:42', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'ocena opisowa - ideał?', 'Sympatyczny i wesoły, potrafi nauczyć początkujących i pozwala pograć zaawansowanym. Nie lubi wystawiać ocen niższych od 5.0 i bardzo stara się tego nie robić. Złoty człowiek!', 'Waga opinii: x1,05', '2013-02-09 17:37', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.0, 'Oj nagrałam się, nagrałam', 'Prowadzący super! Osoby, które na zajęciach miały pierwszy kontakt z tym sportem pod koniec semestru grały na całkiem dobrym poziomie. Kurs godny polecenia, ponieważ korty we Wrocławiu są drogie, a tutaj mamy je za darmo + trenera', '', '2013-02-11 20:35', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('pilka nozna', 5.5, 'ocena opisowa - PO LE CAM', 'zawsze byla rozgrzewka na poczatku zajec (10-20 min), zaliczenie za obecnosc, przy czym mozna bylo latwo sie z nim dogadac (moze dlatego ze mial fajny humorek i flirtowal z jakas babka w recepcji na spartanie )', '', '2013-02-12 01:26', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('futsal', 5.0, 'ocena opisowa - polecam', 'Zajęcia bardzo fajne, na początku zawsze kilkanaście minut rozgrzewki, a później gramy do końca zajęć. Na jego zajęcia lepiej przychodzić punktualnie, bo jak będzie duże spóźnienie to nie wpuszcza na zajęcia', 'Waga opinii: x1,05', '2013-02-13 21:16', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'Bardzo w porządku', 'Profesor Śliwiński nie robi z niczym problemów, można łatwo odrabiać zajęcia, także w przód, daje pograć w piłkę. Nie lubi spóźnialskich i zdarza mu się z nimi rozmawiać indywidualnie ale ostatecznie zawsze okazuje łaskawość. Ogólne wrażenie - bardzo pozytywnie!', 'Waga opinii: x1,05', '2013-02-17 21:43', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal & tenis ziemny', 5.5, 'ocena opisowa - ideał', 'Pan Śliwiński to bardzo pozytywna postać, dobrze potrafi dobrać do siebie ludzi żeby można było pograć na boisku:) zna się na rzeczy, dobrze tłumaczy. Pilnuje tego co się dzieje na boisku i o to chodzi z zaliczeniem bez problemu. POLECAM!', '', '2013-02-18 12:44', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna', 5.5, 'Polecam', 'Zaliczenie za obecności. Na początku rozgrzewka (na każdym wuefie inna!), a potem podział na drużyny i gramy! Na początku mialem zajęcia na hali na niskich łąkach. tam dzieliliśmy się na 3 drużyny i mecze trwały po 5 minut. Potem zajęcia przeniosły się na sztuczną murawe na Sępolno i tam już podział na 2 drużyny. Bardzo fajny wf no i w porządku prowadzący', 'Waga opinii: x1,05', '2013-02-18 16:39', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('futsal', 5.0, 'spoko', 'jest git majonez, najpierw krótka rozgrzewka max. 0,5godz, a potem podział na drużyny i wio. Polecam dla tych co chcą sobie pograć. Jedynym minusem, nawet nie samego prowadzącego, jest miejsce odbywania zajęć, a mianowicie sala uniwerku gdzieś na karłowicach.', '', '2013-02-18 19:42', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'ocena opisowa - Zdecydowanie polecam!', 'Zajęcia interesujące, prowadzone w bezstresowej atmosferze. Ocena za obecności, z każdą nieobecność ocena w dól. Prowadzący jest przyjazny studentowi, nie lubi spóźniania się na zajęcia. Pozwala odrabiać zajęcia w tył i do przodu co jest wielkim plusem! Gorąco polecam.', 'Waga opinii: x1,01', '2013-02-20 11:13', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.5, 'ocena opisowa - bardzo OK', 'bardzo mily prowadzacy, nie robi problemow z zaliczeniem ani z odrabianiem nieobecnosci, jak najbardziej pozytywny Pan, napewno bym sie zapisal do niego po raz drugi', 'Anonymous', '2013-02-20 12:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Squash', 4.5, 'ocena opisowa - polecam', 'Z tym prowadzącym miałem jeden semestr squasha. Jest to człowiek, który stara się czegoś nauczyć studentów. Jeśli widzi, że ktoś sobie nie radzi albo popełnia jakieś błedy to stara się je wyjaśnić i pokazać jak powinno się grać. Zaliczenie na podstawie obecności. Polecam tego prowadzącego ze względu na miły charakter i odpowiednie podejście do studenta.', '', '2013-06-23 01:06', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'ocena opisowa - jak najbardziej polecam', 'Zaliczenie jak wyżej. Prowadzący nieco charyzmatyczny, typowy sędzia piłkarski nie lubiący dyskusji. Spóźnień nie toleruje. Najważniejsze że daje pograć w piłkę i to porządnie. Na uwagę zasługują różne gierki na \'ćwiczenie taktyki\', wariant taktyczny, podział dwóch atakuje, dwóch broni i gramy. Warty polecenia, coś nowego i jak pisał ktoś wcześniej, ciekawa odskocznia od codziennego stresu.', 'Anonymous', '2013-09-24 17:26', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.0, 'Polecam', 'Miałem przyjemność uczestniczyć w zajęciach z turystyki górskiej u tego Pana. Pan Jerzy zapewnił nam wyjścia na ciekawe trasy, o długości do 20km. Zajęcia, lub raczej wyjścia na szlak, wspominam jako bardzo luźne i generalnie bardzo polecam komuś, kto chce spędzić weekendy aktywnie w plenerze. Fajne widoki, świeże powietrze, trochę natury. Zajęcia super. Polecam! Zasady zaliczenia: 5 wycieczek: 5.0 4 wycieczki + jedna odrobiona na zajęciach we Wrocławiu: 4.0 4 wycieczki: 3.0 mniej: 2.0', 'Anonymous', '2014-06-26 22:34', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.5, 'Idealne zajęcia sportowe', 'Prowadzący (razem z mgr Krzysztofem Niewiarą) prowadził zajęcia sportowe zwane turystyką górską. Były to 3 wyjazdy: 1 jednodniowy oraz 2 dwudniowe. System oceniania jakiś tam był, ale jeżeli było się na wszystkich wyjazdach było 5. Jak się na jakimś nie było, to można było odrabiać żeby podnieść ocenę/zaliczyć. Prowadzący nie przejmowali się za bardzo grupą (zamykali szlak idąc na końcu, więc była to gwarancja braku maruderów). Dużo tu nie ma co mówić - po prostu polecam!', 'Anonymous', '2017-01-28 14:09', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.5, 'Polecam', 'Prowadzący jest aktywny na zajęciach, tzn. nie robi tego na odwal się, jak niektórzy. Najpierw mocna, dość męcząca rozgrzewka, potem podział na drużyny i gra. Jako sędzia nie toleruje fauli i mocnych wejść. Jest zwolennikiem gry dla przyjemności, a nie dla wyniku.', 'Anonymous', '2014-07-10 12:14', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 4.5, 'Polecam', 'Świetny trener, fajnie prowadzi zajęcia, rozgrzewka, potem kilka ćwiczeń i gierka. Jeśli będziesz się wyróżniał i pokażesz z dobrej strony w kolejnym semestrze dostaniesz zaproszenie do sekcji, gdzie poziom jest wysoki.', 'Waga opinii: x1,05', '2014-08-18 11:58', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'Jak najbardziej tak', 'Prowadzący w porządku, nie toleruje obraźliwego zachowania, wulgaryzmów, brutalnej gry, co zajęcia rozgrzewka, parę ćwiczeń i chyba to na co wszyscy czekają czyli gierka', 'Anonymous', '2014-09-22 19:41', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('FUTSAL', 5.0, 'ocena opisowa - Bardzo dobry', 'Bezproblemowy prowadzący zajęcia, rozgrzewka, technika i sporo gry, a w dodatku można podszkolić się w zasadach gry w piłkę halową, polecam, kurs przyjemny i porządnie prowadzony', 'Anonymous', '2015-02-24 22:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'spoko', 'ocena za obecność, jesli jestes naprawde dobry to zaproponuje ci przystąpienie do sekcji, najpierw 20-30 min dobrej rozgrzewki a potem cały czas granie', 'Anonymous', '2015-06-14 15:34', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.0, 'Polecam. Przyjemnie i bezproblemowo', 'Jeśli traktujesz poważnie zajęcia, to z panem Śliwińskim da się dobrze żyć. Nie patrzy przychylnie na spóźnialskich, szczególnie na odróbkach (potrafi wyprosić spóźnionych, gdy już nie ma miejsca na korcie) . Generalnie na 5.0 wystarczy mieć prawie wszystkie obecności.', 'Anonymous', '2015-09-10 12:24', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'świetny', 'Świetny prowadzący, bardzo przyjazny dla studentów. Stara się jak najwięcej nauczyć, zwłaszcza tych początkujących. Ocena za obecność. Gorąco polecam!', 'Anonymous', '2015-09-12 12:36', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Piłka nożna halowa', 5.0, 'polecam', 'Dobry prowadzący, nie przepada za spóźnialskimi. Daje pograć, rozgrzewki przeplata z zabawą/ćwiczeniami z piłką, na początku semestru jest tego więcej, później prawie sama gra', 'Anonymous', '2015-09-20 16:01', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.0, 'Bardzo fajne zajęcia', 'Zaliczenie na podstawie obecności, pan Jerzy w razie kłopotów podpowiada, stara się pokazać. Poziom gry prowadzącego jest naprawdę bardzo wysoki - jest się od kogo uczyć', 'Anonymous', '2016-01-25 19:58', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Ping Pong', 5.5, 'Super!!!', 'Bardzo miły i sympatyczny, podpowiada jak grać prawidłowo i lepiej. Można nieźle podszkolić swoje umiejętności. Na zajęciach jedynie turnieje, zwycięzca wygrywa ekstra obecność. Zaliczenie jedynie na podstawie obecności, czyli jak chodzisz to 5.0 bez problemu.', 'Anonymous', '2016-02-06 09:42', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Squash', 5.5, 'Polecam', 'Na pierwszych zajęciach prowadzący wytłumaczy jak grać. Na kolejnych grami już sami, a prowadzący przechodzi się od kortu do kortu i podpowiada co można poprawić, żeby grać lepiej.', 'Anonymous', '2016-09-20 15:05', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.5, 'Polecam', 'Zaliczenie za obecność, dopuszczona jedna nieobecność, jeśli się zmieścisz w limicie, masz pewne 5.0 Na zajęciach prawie sama gra w ramach turniejów, zwycięzca wygrywa dodatkową obecność. Prowadzący bardzo sympatyczny, polecam.', 'Anonymous', '2016-09-29 15:15', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Squash', 5.0, 'Genialny prowadzący wręcz trener osobisty', 'Jeden semestr z tym Panem i umiesz grać. Dosłownie lata i tłumaczy jakie popełniamy błędy, doskonali technikę i udziela świetnych rad. Zaliczenie za obecność. Polecam i to bardzo!', 'Anonymous', '2016-10-05 18:12', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.5, 'Idealne zajęcia sportowe', 'Prowadzący (razem z mgr Krzysztofem Niewiarą) prowadził zajęcia sportowe zwane turystyką górską. Były to 3 wyjazdy: 1 jednodniowy oraz 2 dwudniowe. System oceniania jakiś tam był, ale jeżeli było się na wszystkich wyjazdach było 5. Jak się na jakimś nie było, to można było odrabiać żeby podnieść ocenę/zaliczyć. Prowadzący nie przejmowali się za bardzo grupą (zamykali szlak idąc na końcu, więc była to gwarancja braku maruderów). Dużo tu nie ma co mówić - po prostu polecam!', 'Anonymous', '2017-01-28 14:09', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'Bardzo sympatycznie', 'Prowadzący zna się na rzeczy, zajęcia są prowadzone profesjonalnie i w przyjaznej atmosferze. Można się sporo nauczyć pod kątem zasad. Zdecydowanie polecam', 'Anonymous', '2017-06-24 11:15', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 5.0, 'Super', 'Trzy wyjazdy, zaliczenie za obecność. Atmosfera bardzo luźna, zwykle prowadzący (razem z panem Niewiarą) szli na końcu. Na jeden wyjazd (jednodniowy z własnym dojazdem) zdarzyło mi się spóźnić i nie zastać grupy na miejscu zbiórki, więc weszłam na szczyt sama, tam złapałam resztę, a prowadzący bez żadnego problemu dopisał mnie do listy, więc zdecydowanie jest bardzo bezproblemowo.', 'Anonymous', '2017-07-27 22:14', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.5, 'Świetny gość!', 'Bardzo miły prowadzący, idący na rękę studentowi. Można z nim dogadać dosłownie wszystko. Ma poczucie humoru, lubi sobie pożartować, zajęcia w bardzo dobrej atmosferze(chyba że się go bardzo zdenerwuje ) Podczas gry czy ćwiczeń podpowiada i pomaga aby jak najlepiej się wyszkolić w danej dziedzinie. Polecam na każdy kurs sportowy!', 'Anonymous', '2018-02-08 17:28', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'Polecam', 'Przyjemny kurs, zaliczenie za obecność, nieobecności można odrabiać na innych zajęciach tego prowadzącego. Na początku rozgrzewka i jakaś taktyczna gierka, a potem wybór składów i gra. Polecam, miła odskocznia od innych zajęć.', 'Anonymous', '2018-06-30 17:55', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Squash', 5.5, 'Polecam!', 'Bardzo przyjemnie poprowadzone zajęcia. Grupa jest podzielona tak, że gramy z przeciwnikami na swoim poziomie. Co jakiś czas są wplatane ćwiczenia z techniki gry. Wszystko w bardzo miłej atmosferze. Zdecydowanie polecam!', 'Anonymous', '2019-01-24 23:09', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'Co tu dużo mówić, przyjemność!', 'Szkoda, że zaplecze tenisowe jest tak bardzo niedofinansowane... Ale zajęcia pana Śliwińskiego sa bardzo przystępne dla tych co grali długo i dla tych co nie grali wcale, także każdy znajdzie coś dla siebie. Gorąco polecam każdemu, kto ma problem z wybraniem WFu.', 'Anonymous', '2019-02-05 21:57', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.5, 'ŚWIETNIE!', 'W mojej opinii, zajęcia te były prowadzone dokładnie tak jak powinno, szybka rozgrzewka, trochę taktycznych gierek, uczenia paru schematów, a potem granie, bez uprzykrzania życia. Zaliczenie to obecności, każda jedna to ocena niżej, jedna nieobecność do wykorzystania. P. Śliwiński lubi porozmawiać z siedzącymi aktualnie na ławce o aspektach gry, ogólnie o sporcie, po prostu ogólnie bardzo przyjemna osoba!', 'Anonymous', '2019-07-23 22:40', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.0, 'Przyjemne zajęcia', 'Na zajęciach stacjonarnych, 5 min rozgrzewka i granie przez całe zajęcia. Nie dało się nudzić, ponieważ Pan Śliwiński zawsze tak rotował stołami, żeby każdy grał z kilkoma osobami. Zawsze był miły i przyjazny, czasami nawet sam włączał się do gry grając z kimś na jakimś stole. Na zdalnym 30-40 min. wstępu teoretycznego, który polegał na wysłaniu odpowiedzi na pytania na teamsach na podstawie materiałów, które wysłał Pan Śliwiński. Była to bardziej formalność, aby potwierdzić obecność na zajęciach. Później część praktyczna, czyli ćwiczenia przed kamerami. Pan Śliwiński prowadził tą część, były to raczej lekkie ćwiczenia, na których trudno było o zmęczenie. Bardzo przyjemne i bezstresowe zajęcia. Bardzo polecam.', 'Anonymous', '2022-02-02 09:20', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis ziemny', 5.5, 'Totalny szef', 'Brać w ciemno jeśli tylko jest taka możliwość. Zajęcia prowadzone świetnie, każdy może się czegoś nauczyć, nawet gdy nigdy nie miałeś rakiety w ręce. Zaliczenie samą obecnością. Na zdalnych też prowadził fajnie, najpierw pół godzinki jakiejś teorii czy omawiania aktualnych nowinek z tenisowego świata, a później 2 serie obwodu.', 'Anonymous', '2022-02-02 12:16', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Futsal', 5.0, 'Szybka rozgrzewka i gramy w gałę', 'Bardzo miły, prostudencki prowadzący. Zajęcia z nim, nawet po przejściu na formę zdalną, to czysta przyjemność. Zaliczenie z samej obecności, nic dodać, nic ująć, brać w ciemno.', 'Anonymous', '2022-02-16 11:39', 5);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Tenis stołowy', 5.5, 'Super', '[hybrydowo] Na zajęciach stacjonarnych było bardzo luźno. Na początku krótka rozgrzewka, a potem już tylko graliśmy. Ocena to tylko obecność. Zdalnie na początku dostawaliśmy plik z zadaniami, który trzeba było oddać w określonym czasie. Naprawdę polecam.', 'Anonymous', '2022-02-18 07:59', 5);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Zemankiewicz K', 'mgr', 4.91, 't,zemankiewicz-k-mgr,54');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Narciarstwo', 5.5, 'Bardzo przyjemny kurs', 'Mega fajne zajęcia, każdego dnia najpierw trochę zajęć z doskonalenia techniki jazdy pod jego okiem, a potem już jazda wolna. Sympatyczny, rzeczowy prowadzący, który zna się na nartach. Polecam!', 'Anonymous', '2018-01-27 14:45', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Zemankiewicz K, mgr Taniec Ocena: spoko', 4.0, '', 'Ocene daje za chodzenie, można bezkarnie opuścić jedne zajęcia, jeśli jest więcej to jeśli chcesz mieć 5 to musisz je odrobić, ponadto każdy musi raz przeprowadzić rozgrzewkę przy muzyce (to może być co kolwiek od zabawy z balonami po rozciąganie, cokolwiek Ci do głowy przyjdzie) jeżeli chodzi o nauke tańca to nie da się tego wykonać przy jednych zajęciach tygodniowo, można się jedynie dobrze nuczyć podstaw i etykiety, zajęcia są prowadzone tak by jak najwięcej czasu było poświęcone na taniec (nie obawiajcie się tego że nie macie partnera system zapisów jest tak skonstuowany że ilość miejsc dla studentów i studentek jest taka sama)', '', '2006-02-15 23:39', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokeja', 5.0, 'Ocena: SUPER, polecam !', 'Ja miałem z tym panem co prawda kurs  ale, ale  5.0 za wszystkie obecności, jedna możliwa bez odrabiania, więcej - trzeba odrabiać jeśli chce się mieć piateczke. Kurs fajny i przyjemny ale trzeba się nabiegać za piłeczką, dlatego często stawałem na bramce zero stresu, żadnych testów czy innych pierdoletów, na początku rozgrzeweczka, wybór drużyn i jazda. Polecam gorąco.', '', '2006-02-18 19:58', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona', 4.0, '', 'Miałem z tym panem samoobronę. Polecam. Kurs ciekawy, można się czegoś nauczyć ( nie za wiele bo mało czasu ale podstaw tak). Tak jak koledzy wspomnieli, jedna dozwolona nieobecnośc, kolejne trzeba odrabiać bo ocena leci w dóóół ;/ Nie zostawiajcie zajęc do odrobienia na konic semestru bo mozecie się zdziwić.... robi problemy ;/ "Trzeba było się wcześiej za to zabrac" ;/ . Za fuul obecność daje 4,5. Przedostatnie zajęcia to walki 1 na 1. Jeśli się pokażesz z dobrej strony i wygrasz w swojej aktegorii wagowej podnosi ocenę. Idziesz odrabiać do niego zajęcia? .... pełna kultura !!! bez: " Dzień dobry. Czy mógłbym/mogłabym uczestniczyć w tych zajęciach?" NIE DA RADY!! Wyczulony na tym punkcie. jesli o tym nie zapomnisz to będzie luzzz.', '', '2006-02-21 22:48', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona', 4.0, 'scythe', 'Mniej wiecej zgadzam się z tym co wspomnial , lecz pozwole soebie jeszcze usupełnić: Cytat: Za fuul obecność daje 4,5. Przedostatnie zajęcia to walki 1 na 1. Jeśli się pokażesz z dobrej strony i wygrasz w swojej aktegorii wagowej podnosi ocenę. 5 można dostać także pokazując czego się nauczyło wciągu tych zajęć. W dniu wpsiów p. Z. prosi o rozłożenie indeksów na dwie kupki - \'ocene i do domu\' lub \'wyższą ocene i pokazywnie umiejętności\'. Tak wiec nie nastawiłbym sie u niego wogóle na te walki (które przynamniej w moim odczucu byly conajmniej dziwne, np. w mojej grupie wagowej byly sędziowane przez osobę nazwijmy to niedoświadczoną [\'pierwszą z brzegu\'] zamiast przez trenera), ale za to nieodpuszciłbym sobie wykazywania sie na ocene 5 (z 4,5) z tego co widzialem/słyszałem wszytscy którzy pokazywli czego się nauczyli mieli podwyższoną ocene. Tak wiec jesli macie okazje to nie olewajcie sobie ostatnich zajec, bo to malo zachodu a 0,5 w górę. Niestety co do samego prowadzącego mam już obekcje, z punktu wdzienia treningu itd. wszytko było ok (a czesami nawet bardzo ok - rozgrzewki w formie zabawy), ale niestety miala miejse u nas na treningu sytulacja ktora bardzo mnie do tego pana zrazila; podczas pokazywania dźwigni na noge (stopę) zignorował zupełnie odklepenie w mate (czyli powiadomienie o tym, że ma się dość, że boi) studenta na ktorym pokazywal technike i nie puścił lub chociaż zmniejszył nacisku (siłę skrętu). Efekt taki, ze choć szczeknelo/chrupneło, pomocnik się zwinał z bólu na wskutek doznanej kontuzji., która zresztą wykluczyła go z udziału w zajęciach na dobre paru treningów. Coż, może był to wypadek przy pracy (zdarza się ), jednak mnie ten \'wypadek\' bardzo do pana Z. zraził. Choć trzeba przyznac, ze poza tym to zasługje na bardzo dobrą ocene: poczucie humoru, prowadzenie zajęć, ogólnie ok itd.', '', '2006-02-22 10:26', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, '', 'Jestem zadowolna z kursu. Nie czuje sie krolowa parkietu, ale czegos sie z pewnoscia na zajeciach nauczylam. Jak sie chodzi, to bez problemu ma sie 5. Jak sie cos opusci, to mozna odrobic (najlepiej u niego), nie stwarza problemow. Ogolnie spoko koles:) Twierdzi,ze wf jest najwazniejszym przedmiotem... .. .. .. a dlczego tak? bo inne przedmioty raczej Wam tak sredniej nie podwyzsza;-)', '', '2006-06-14 23:32', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 4.5, 'OK', 'Pan Zemankiewicz to człowiek z zasadami - jak raz coś powie to dotrzymuje słowa. Oczywiście tego samego wymaga od innych, więc trzeba się pilnować. Podczas ćwiczeń na siłowni opowiada różne ciekawostki, dotyczące prawidłowego ich wykonywania, oraz co się dzieje, gdy coś źle ćwiczymy. Posiada szeroką wiedzę na temat budowy i funkcjonowania ludzkich mięśni i chętnie dzieli się nią ze studentami. Za samą obecność na wszystkich zajęciach (minus jedno) otrzymujemy 4.5, a żeby otrzymać 5.0 należy raz w semestrze przeprowadzić rozgrzewkę (czepia się), bądź na koniec wykonać jedno z wymyślonych przez prowadzącego ćwiczeń (co nie jest łatwe).', '', '2006-10-03 19:32', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.5, 'Gorąco polecam', 'Facet naprawde wporządku! Jak ty z kultura do niego to on do Ciebie też! Zaliczenia na zasadzie obecności. odrabiać mozna 2 nieobecności Jedyny mankament to taki ze czasem nie patrzy na gre, nie ma kto gwizdac i robią sie problemy w spornych sytuacjach. ale nie rzutuje to na całokształt oceny!!', 'Waga opinii: x1,04', '2006-12-26 15:35', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('taniec', 4.5, 'ocena opisowa - może być', 'ogólnie nie najgorzej, czasem pan się czepia, ale zajęcia naprawde ciekawe. czyli może być.', '', '2007-01-18 20:04', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona (dla początkujących)', 5.5, 'ocena opisowa - polecam, polecam, polecam!', 'Generalnie zgadzam się z tym, co napisano powyżej: pan Zemankiewicz jest bardzo sympatyczny, życzliwy dla studentów, wcale nie taki surowy i trzymający się bezwzględnych reguł, bo paru studentom odpuścił mimo nadmiaru nieobecności i zaliczyli, ma duże poczucie humoru i było naprawdę bardzo miło mieć z nim WF. Stara się przekazać jak najwięcej umiejętności, po kilka razy demonstruje różnego rodzaju rzuty, dźwignie itd., czasem pokaże coś specjalnego dla dziewczyn (np. w stylu co zrobić jak ktoś szarpie za włosy albo wyrywa torebkę ). Ktoś wyżej pisał, że była nieprzyjemna sytuacja, związana z kontuzją ucznia. Od siebie mogę powiedzieć tyle, że podczas mojego kursu p. Zemankiewicz zawsze dbał o to, żeby wszyscy byli dobrze rozgrzani, żeby w czasie wykonywania ćwiczeń przestrzegano zasad, żeby nie stosować niedozwolonych technik (np. atak na szyję w pozycji stojącej) i przede wszystkim, żeby demonstrując coś na studencie go nie uszkodzić (ale przyznał się, że niestety wypadku różne były i jak coś boli w czasie pokazywania to szybko trzeba odklepywać). Niestety mimo to parę kontuzji było - a to kolega nie mógł szyją ruszyć, a to ktoś źle spadł i obtłukł bark, były też przypadki wsadzania paluchów w oko i skręcone kolano - ale za to prowadzącego nie można winić. Cóż, zdarza się. Najlepszym sposobem na uzyskanie dobrej oceny jest po prostu 100% obecność - bez odróbek itd. i nie powinno być kłopotu, żeby mieć 4,5 - 5,0. Są też te walki (ale odnosząc się do tego co napisano powyżej - w mojej grupie nie były sędziowane przez "pierwszego z brzegu", ale przez p. Zemankiewicza, ew. studenta, którego tenże na wszelki wypadek kontrolował stojąc z boku, czy dobrze sędziuje). Może jeszcze dwa słowa o samym kursie, bo pamiętam, że zapisując się sam byłem ciekaw jak to wygląda . Otóż zajęcia składają się zawsze z rozgrzewki (na początku bardzo długa, potem trochę krótsza), ćwiczenia padów, ćwiczenie technik i po jakichś 4-5 zajęciach walki w parterze i 3 ostatnie zajęcia walki na stojąco (przy czym położony jest nacisk na judo wg zasad sportowych, a nie taką czystą samoobronę, że np. wolno kopać w krocze ). Moim zdaniem jak na taką ilość godzin nauczyć się można zaskakująco sporo, ale i tak za mało, żeby można było się było jakoś bardzo skutecznie bronić - dlatego po tym kursie warto zapisać się na SAMOOBRONĘ DLA ZAAWANSOWANYCH albo JUDO DLA ŚREDNIOZAAWANSOWANYCH (tam już ludzie coś konretnego robią - na jedne zajęcia przyszedł do nas z grupy zaawansowanej jeden student na odróbkę i w walkach bez problemu z wszystkimi wygrywał ).', '', '2007-01-27 03:00', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 4.5, 'OK', 'Tak jak wyzej, zajecia fajne, ocena za obecnosc. Polecam.', '', '2007-02-01 14:59', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona', 5.0, 'W pelni polecam!!', 'Czlowiek wporzadku, z dobrym poczuciem humoru. Choc to tylko 1,5 h w tygodniu i wiadomo ze nie da rady sie nauczyc wszystkiego to dla ludzi z jakims doswiadczeniem moze to byc niezle doswiadczenie i przypomnienie. Zawsze chetnie tlumaczy i pokazuje. Co do zaliczenia to oprocz tego co napisali moi poprzednicy, wystarczylo sie pokazac z dobrej strony i byc w miare sumiennym zeby miec 5.0. W skrocie jesli chcesz sie czegos nauczyc to goraco polecam!!', '', '2007-02-05 13:00', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 5.0, '', 'Taniec polecam Bardzo mily Pan. łatwo u niego zaliczyć. wytarczy być na wszystkich zajęciach i ma się 5,0', '', '2007-02-06 18:51', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, 'ocena opisowa - polecam', 'Zajecia prowadzone bardzo fajnie, prowadzacy wie czego chce nas nauczyc i niezle mu to wychodzi, w dodatku bardzo dobrze tanczy. Starczy byc na 14 zajeciach i poprowadzic rozgrzewke i ma sie 5,0 bardzo sympatyczna atmosfera na zajeciach', '', '2007-02-09 13:56', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('samoobrona', 3.5, 'ocena opisowa - srednio na jeza', 'Uwazam, ze ten pan jest niezbyt ciekawym wyborem jesli chdozi o wf jako taki. Jak ktos sie chce nauczyc walczyc (podstaw) to tez chyba niezbyt wiele mu ten kurs da. Jesli ktos chce tylko przejechac wf to troche sie zmeczy i na wyjsciu za obecnosci ma 4,5. No i jeszcze z odrabianiem sa male jaja bo mozna tylko na jego kursy przyjsc a on z samoobrony malo ich prowadzi by dobrac sobei termin. Jednym slowem: Polecam tym, ktorzy czasem lubia miec pod gorke', '', '2007-02-18 22:13', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 4.5, '', 'mgr Zemankiewicz jest w porządku, ciężko o nim powiedzieć, żeby miał przyjazne usposobienie ale nie ma też na co narzekać. Chodziłam do niego na Taniec, w sumie ciekawe zajęcia ale Gubernat jest sympatyczniejsza i lepsza w nauczniu. Jedyny mankament to taki ze Gubernat ma zajecia tam gdzie psy...:) Podsumowując: polecam taniec u mgr. Zemankiewicza', 'Waga opinii: x1,03', '2007-02-21 15:53', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('samoobrona', 4.0, 'ocena opisowa - w porzadku', 'wf meczacy bardzo, sporo ciekawych rzeczy mozna sie nauczyc, prowadzacy profesjonalnie podchodzi do zajec, ogolnie na wfie panuje luzna atmosfera, zaliczenie za obecnosci - uczciwe!', '', '2007-06-28 13:36', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 4.5, 'OK', 'Bardzo konkretny prowadzący z zasadami. Na pierwszych zajęciach podchodzi bardzo profesjonalnie. Później po prostu wybieraliśmy się i była gierka. Raz czy dwa razy zagrał z nami. Ogólnie atmosfera luźna, bez zastrzeżeń.', '', '2008-01-23 17:58', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('siatkówka', 5.0, 'ok', 'Możliwa jedna nieobecność bez wpływu na ocenę końcową. Strasznie długie rozgrzewki były . Ogólnie może być .', 'Waga opinii: x1,25', '2008-01-24 18:30', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona', 4.5, 'ocena opisowa - ok', 'Zasady zaliczenia jak powyżej już ktoś opisał. Ja miałam bonus, w postaci wyższej oceny i nie musiałam brać udziału w ostatnich walkach- byłam jedyna dziewczyna w grupie .', '', '2008-02-14 10:53', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec!!', 5.0, 'bardzo polecam', 'Jeden z fajniejszych wfów na jakich byłam; prowadzący bardzo konkretny - wie czego chce nas nauczyć, a przy tym świetnie tańczy; zajęcia bardzo wciągające, także chodzi się na nie z przyjemnością; ocena za obecność + jedną rozgrzewkę trzeba poprowadzić (może być na wesoło, ale przechodzi także tradycyjna); w różnych grupach różne tańce są; ćwiczy się dany taniec do skutku - aż grupa w miarę będzie sobie z nim radziła; u nas szło to bardzo topornie ogólnie zajęcia przyjemne', '', '2008-02-17 13:16', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.0, 'ocena opisowa - może być', 'Zaliczenie przez obecności - no czego chcieć więcej? Nie robi raczej problemów z odrabianiem, ale trzeba się konkretnie umawiać. Komplet obecności bez jednej to dalej 5, potem odpowiednio o ocenę niżej za każdą kolejną absencję ;p', '', '2009-01-28 18:49', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 4.5, 'W porządku', 'Pan Zemankiewicz jest człowiekiem bardzo profesjonalnie podchodzącym do swoich obowiązków. Jeśli ktoś czegoś od niego chce, musi się z nim konkretnie dogadać. Na zajęciach w porządku, zero stresu, krótka rozgrzewka (czasami bez), podział na zespoły i jazda. Polecam tym, którzy lubią duuuuużo biegać.', '', '2010-06-15 13:59', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.0, 'ocena opisowa - POLECAM !!!!', 'Jak wyżej... 5.0 w indeksie za obecności. W porządku człowiek. Zabawny czasami. I jeśli chodzi o sport lub różnego rodzaju ćwiczenia na różne partie mięśni posiada dużą wiedzę.', '', '2010-06-15 14:31', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec towarzyski', 5.0, 'polecam dla tych co lubią tańczyć', 'kurs jest ok, ocena za obecności, można mieć jedna nieobecność , a kolejne trzeba usprawiedliwiać. Trzeba przynajmniej raz przeprowadzić rozgrzewkę, ale to nie jest jakies stresujące. Można nauczyć się podstawowych kroków tanecznych.', '', '2011-02-13 19:34', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec towarzyski', 5.5, 'ocena opisowa - polecam', 'Prowadzący jest miły, czasami żartuje. Ocena za obecności (można mieć jedną nieobecność bez zmiany oceny) + przeprowadzenie jednej/dwóch rozgrzewek. Są one proste - grunt, by przynieść muzykę i jakoś machać rękami i nogami przez 3 minuty Nieobecności można odrabiać i wtedy liczą się one jako zwykłe obecności (czyli nie obniżają oceny). U mnie w grupie uczyliśmy się bluesa, polki, samby, walca, jive\'a, english pop house\'u i salsy. Czyli całkiem sporo Żałuję tylko, ze nie było tanga Wiem, ze u innej grupy był jeszcze rock\'n\'roll, który wyglądał bardzo fajnie Bardzo polecam - są to zajęcia bardzo przyjemnie, można się nauczyć tańczyć i co najważniejsze - są całkowicie bezstresowe. Nawet największe łamagi mogą na to iść', '', '2011-02-13 19:51', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Narciarstwo', 5.5, 'Bardzo przyjemny kurs', 'Mega fajne zajęcia, każdego dnia najpierw trochę zajęć z doskonalenia techniki jazdy pod jego okiem, a potem już jazda wolna. Sympatyczny, rzeczowy prowadzący, który zna się na nartach. Polecam!', 'Anonymous', '2018-01-27 14:45', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec towarzyski (podstawy)', 3.0, 'ocena opisowa - ujdzie w tłoku', 'Kurs sam w sobie bardzo fajny. Ale jezeli nie jesteś urodzonym tancerzem to nie przypadniesz p. Zemankiewiczowi do gustu. Ma dziwne poczucie humoru, oraz swoje nieugięte zasady. Każdy musi prowadzić 2 razy rozgrzewkę (aczkolwiek wiekszość prowadziła raz). Często nie zaliczał ludziom rozgrzewek, ale akurat temu sie nie dziwie, bo wielu z nich do nich sie w ogóle nie przykladało. Dodatkową wadą było to, że prowadzący prowadził zajęcia do ostatniego dnia. Moze akurat mojej grupy nie lubił p.Zemankiewicz bo np grupa z tego samego kursu skonczyla zajecia 2 tygodnie przed nami. Zaliczenie oczywiscie za obecnosci, można raz nie przyjsc bez konsekwencji.', '', '2011-02-16 12:29', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej [WF] + [sekcja]', 5.5, 'człowiek sympatyczny. człowiek z zasadami.', 'Sama przyjemność współpracy. Warunki od początku jasno określone i bardzo pro-studenckie. Ale za to przestrzegane rygorystycznie - promujemy systematyczność. I nic więcej. Obecności do piątki zupełnie wystarczą. Człowiek obowiązkowy i z poczuciem humoru. Nauczy, pomoże, ale jeśli chcesz. Jeśli przychodzisz "żeby zaliczyć" i nic więcej Cię nie interesuje, to spoko, chodź sobie, biegaj, graj, ale nie licz na szczególne względy czy większe zainteresowanie. Przy okazji zachęcam do pojawienia się na sekcji. Ludzi nigdy za wiele, a grupa fajna i otwarta na nowych członków drużyny.', '', '2011-06-21 01:22', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('taniec towarzyski', 5.0, 'ocena opisowa - łooo! Super!', 'Pan Krzysztof super człowiek, poczucie humoru takie, jak być powinno. Ma genialne podejście do studenta, nie spina, jeśli go szanujesz. Ocena za obecności, rozgrzewkę trzeba przynajmniej raz przeprowadzić, MINIMUM 3 minuty. Na przedostatnich zajęciach turniej tańca towarzyskiego - czyli wytańczenie wszystkiego tego, czego się nauczyliśmy przez cały semestr. Ci, który są na pudle (1, 2, 3 miejsce) dostają tego samego dnia co turniej wpis do indeksu, pozostali muszą przyjść na ostatnie zajęcia. Ponadto para, która wygrała turniej, dostaje 5,5.', '', '2012-01-25 01:51', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Jogging', 5.5, 'warto!', 'Prowadzacy bardzo sympatyczny, zyciowy. Czesto mowi o swoich przygodach, rzuci jakims zartem. Co do nieobecności, można mieć jedną i nadal dostanie się 5, reszta musi byc odrobiona, chyba, ze sie wyrozniasz i pokazujesz, ze lubisz jego zajecia to nawet jak masz 2-3 nieobecnosci daje 5 (tak bylo w moim wypadku). Jesli masz mozliwosc - warto!', '', '2012-02-10 11:05', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec towarzyski', 5.5, 'ocena opisowa - bardzo polecam', 'Prowadzący ma świetne podejście do studenta, poczucu humoru, jest miły i symaptyczny. Ogólnie zajęcia przeprowadzane są na luzie, prowadzący nie wymaga, żeby każda para świetnie tańczyła. Sporo się nauczyliśmy przez semestr, na końcu jest konkurs tańca i para, która wygrywa dostaje ocenę 5,5. Jeśli grupa jest słabsza to prowadzący stara się nauczyć mniej rodzajów tańca, a lepiej. Ocena jest wystawiana za obecność. Jedynie trzeba poprowadzić raz albo dwa razy rozgrzewkę.', '', '2012-02-10 12:33', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Turystyka górska', 4.5, 'OK!', 'Zazwyczaj 3 wyjazdy - 2x2 dni + jednodniowy. Zajęcia - bardziej rekreacja niż sport. Zazwyczaj zbiera jeszcze 2 grupy z dwoma prowadzącymi zamawia autokar i nie trzeba tułać się pociągami. Jak są miejsca można wybrać się w góry nie będąc zapisanym na kurs.', '', '2012-02-12 19:25', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 4.5, 'Spoko', 'Zaliczenie za obecnosc, pozniej sam zaczal brac udzial w rozgrywkach. Troche mozna sie nauczyc, duzo pobiegac, za marudzenie kazal ludziom prowadzic rozgrzewke :p Stosunek do studenta raczej bezproblemowy, mozna bylo sobie pogadac nie tylko o tematach zwiazanych z przedmiotem.', 'Anonymous', '2012-03-16 10:58', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.0, 'ocena opisowa - Polecam!!', 'Pan Zemankiewicz jest bardzo konkretną osobą. Ma swoje zasady, których należy przestrzegać a kurs będzie miły, łatwy i przyjemny, o co zresztą chodzi. Zaliczenie wygląda następująco: 4,5 za 100% obecności, 5 jeżeli dodatkowo przeprowadzisz rozgrzewkę na początku zajęć. Podczas ćwiczeń prowadzący podchodzi i tłumaczy jak należy prawidłowo wykonywać dane ćwiczenie, mówi co robimy źle i pomaga nam to poprawić. Czasami dla urozmaicenia sam prowadzi zajęcia mówiąc nam co mamy wykonywać. Ogólnie bardzo polecam, jednak jeśli nie lubisz ćwiczyć i chcesz po prostu zaliczyć kurs to zapisz się do kogoś innego.', '', '2012-03-19 17:13', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('', 4.0, '', 'Turystyka górska Ogólnie spoko Prowadzący ale robi problemy z odróbkami pod koniec semestru. Ma poczucie humoru i dobre podejście do studenta. Za jedna nieobecność na wyjeździe dostajesz 3 jeśli chcesz mieć 5 musisz odrobić ten wyjazd u innego prowadzącego w innym wypadku możesz mieć 4 odrabiając 3 zajęcia sportowe (dowolne).', 'Waga opinii: x1,01', '2012-05-26 21:44', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Samoobrona', 4.5, 'ocena opisowa - spoko!', 'Kurs fajnie prowadzony. Nacisk kladziony jest na techniki Judo. Trochę sztywne zasady zaliczenia bo czepiał sie frekwencji. Nie postawil gorszej oceny niż 4.0 Ogolnie polecam', 'Anonymous', '2012-06-02 21:29', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('taniec towarzyski', 5.0, 'ocena opisowa - polecam', 'Konkretny i sympatyczny. Generalnie wymaga obecności - wszak tańczy się w parach, więc lepiej, aby frekwencja była wysoka. Jedną nieobecność można było mieć bez konsekwencji. Tempo zajęć dostosowuje do poziomu grupy. Czasami pozwala wybierać, czego grupa się chce nauczyć.', 'Anonymous', '2013-02-05 02:22', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.5, 'ocena opisowa - świetne zajęcia', 'Obecności trzeba mieć ale zajęcia prowadzone bardzo pozytywnie. Pan Zemankiewicz jest bardzo pozytywnym, z poczuciem humoru człowiekiem. Na tych zajęciach naprawdę można się wyszaleć a zaliczenie za obecność więc nie ma żadnych problemów.', 'Waga opinii: x1,05', '2013-02-14 14:09', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec Towarzyski', 5.0, 'ocena opisowa - ok, ale za mało godzin by nauczyć się tańczyć', 'Zajęcia prowadzone w sposób przyjazny, na początku rozgrzewka, potem tańce, na przedostatnich lub ostatnich zajęciach u nas odbył się mini turniej tańca. Rozgrzewkę każdy ma przygotować raz (ja miałem okazje wykazać się 2 razy). Niestety liczba godzin jest zbyt mała by nauczyć się dobrze tańczyć zwłaszcza jak ktoś łapie trochę wolniej. Mimo to była piątka. Zasady zaliczenia na pierwszych zajęciach i takie są aż do końca.', 'Anonymous', '2014-02-24 22:06', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Koszykówka', 5.0, 'ocena opisowa - polecam', 'W zasadzie nie wiem w jaki sposób wuefista na polibudzie miałby nie być w porządku. Tutaj nie jest inaczej. Dopuszczalna jedna nieusprawiedliwiona i nieodrobiona nieobecność na ocenę 5.0. Atmosfera ok, czasem Pan Trener próbuje nauczyć grupę czegoś ciekawego, ale i tak głównie na zajęciach się po prostu gra w kosza na luzie. Polecam', 'Anonymous', '2014-06-19 12:07', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.5, 'Dla tych, którzy chcą spędzić miło wf i przy okazji się czegoś nauczyć:)', 'Prowadzący jest konkretny i konsekwentny- zasady zaliczenia są jasno określone na pierwszych zajęciach i nie są zmieniane. Zaliczenie jest za obecności. Dwie można odrobić. Ocenę można sobie podnieść zdobywając miejsce na pudle w mini turnieju, który odbywa się na końcowych zajęciach (nic strasznego;) ). Przyznam, że wahałam się co do wyboru tego prowadzącego, ale to był strzał w 10. Pan Zemankiewicz wprowadza świetną, miłą atmosferę, dzięki czemu zajęcia upływają bardzo szybko i wychodzi się z nich z uśmiechem na twarzy. Program zajęć obejmuje tańce standardowe, latynoamerykańskie, możliwe również tańce użytkowe, w zależności od przyswajania przez grupę nowych kroków. Raz mieliśmy możliwość wyboru, który taniec chcemy ćwiczyć:) Podsumowując, polecam wszystkim, którzy lubią tańczyć, chcą się nauczyć paru kroków albo po prostu tym, którzy chcą spędzić miło czas w fajnej atmosferze:)', 'Anonymous', '2014-06-27 00:30', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.5, 'świetnie jest', 'Zaliczenie za obecność, świetna atmosfera, duże poczucie humoru, wszystko jak najbardziej na plus. Prowadzący trzyma się swoich zasad i nie lubi kiedy się je łamie, nie toleruje spóźnień.', 'Waga opinii: x1,05', '2014-09-09 17:35', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, 'polecam, jak ktoś lubi taniec', 'Jest świetnie, jeśli ktoś wie, że będzie chodził, i będzie się dobrze bawił. Nie ma spóźniania, jedna nieobecność obniża ocenę. Radzę dobrze na początku przeczytać regulamin. Można się wiele nauczyć. My zdążyliśmy przerobić walca, bluesa, english party house ( albo coś podobnego ; D ), salse, rock\'and\'rolla. Na ostatnich zajęciach wewnętrzny pokaz tańca, pan nas ocenia i sami siebie oceniamy. Ogólnie jest fajnie, można poznać świetnych ludzi. Polecam!', 'Anonymous', '2014-09-14 11:39', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.0, 'polecam', 'Na pierwszych zajęciach prowadzący przedstawia zasady panujące na jego zajęciach oraz zasady prowadzenia kursu. Ocena na podstawie obecności. Sam prowadzący jest zabawny, zagaduje studentów, opowiada ciekawe historie. Polecam', 'Anonymous', '2014-09-14 13:35', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.0, 'ocena opisowa: polecam serdecznie', 'Zasady zaliczenia prawie jak na każdym WF-e, 5 za obecność, jednak trzeba było odrobić każdą nieobecność, zajęcia odbywały się w przyjaznej atmosferze.', 'Anonymous', '2014-09-25 10:22', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Zajęcia sportowe - kulturystyka', 4.5, 'ocena opisowa - spoko', 'W porządku facet, jednak utrzymuję dyscyplinę i ma swoje zasady; nie można się obijać, gadać za dużo z innymi, słuchać swojej muzyki i spóźniać się (kilka razy pod rząd nie wpuścił na zajęcia jednej osoby, bo się spóźniła kilka minut, potem wszyscy już zaczynali się schodzić 30 min przed zajęciami ). Zawsze chętnie doradzi, pokaże, podczas ćwiczeń poopowiada jakieś ciekawostki i przemyślenia, typu że musimy ćwiczyć też ciało, a nie tylko mózgi, bo coś te mózgi musi potem zaprowadzić do pracy (no ale taka jest prawda):P. Zazwyczaj każdy ćwiczy jak chce, kilka razy nam zrobił obwody z pulsometrami, żeby pokazać nam coś nowego. Standardowo chyba ocena za obecność; jedna do wykorzystania, dwie można odrobić, potem ocena leci w dół, jak chce się mieć 5 to trzeba zrobić jakąś rozgrzewkę (ale u nas w grupie nikt nie był chętny), jak nie to 4,5 Do dzisiaj jak ćwiczę to korzystam z jego rad . Generalnie to polecam, nawet tym, którzy nie mieli się na co zapisać i chcą po prostu mieć zaliczony wf, no ale wiem że u innych jest luźniej (sam tego doświadczyłem na odróbkach, ale mimo tego i tak nie żałowałem tego z kim normalnie miałem te zajęcia)', 'Anonymous', '2015-01-24 17:37', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Jogging', 5.5, 'ocena opisowa - bardzo pozytywnie', 'Nie miałem okazji spotkać się z wuefistą, który by nie był w porządku i Pan Zemankiewicz żadnym wyjątkiem od tego nie jest. Zajęcia prowadzone luźno, tempo biegu na ogół tak dobrane, by mniej wytrzymali też jakoś dawali radę, choć bardziej doświadczeni mogą się ciut nudzić. Zasady zaliczenia były bardzo jasno określone i bezwzględnie przestrzegane - bazowo 5.0 za obecność, jedna dozwolona, każda kolejna to ocena w dół, przy czym nie ma problemów z odrabianiem zajęć. W czasie biegu często można było smakowicie podyskutować i pożartować na różne tematy, nie tylko sportowe. Podsumowując - jak masz możliwość, to zapisuj się bez wahania, a nie pożałujesz.', 'Anonymous', '2015-01-28 21:13', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec U', 5.5, 'Bardzo polecam!', 'Coś dla tych co się chcą dobrze bawić oraz czegoś nauczyć. Zajęcia bezstresowe, Pan pozytywnie nastawiony, miły, nikogo nie obraża. Na koniec wszyscy dostali cukierki Polecam!', 'Anonymous', '2015-06-18 20:25', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('jogging', 5.5, 'Bardzo polecam!', 'Bez stresu, bez wysiłku (tylko ten fizyczny). Po prostu trzeba chodzić na zajęcia i tyle. Jedna nieobecność dopuszczalna resztę trzeba odrobić. Z zaliczeniem i dogadaniem się nie ma problemu.', 'Anonymous', '2015-09-16 01:22', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, 'Bardzo w porządku', 'Prowadzący zabawny, sympatyczny. Ocena końcowa wystawiona za obecności 2 to pół oceny w dół, 3 ocena w dół itd. , a dla zwycięzców "turnieju" odbywajacego sie na ostatnich zajęciach ze wszystkich nauczonych tańców 5.5. Pan Krzysztof nie lubi spóźnialskich. Podobno nie wpuszcza po 15 minutach a 1 min spóźnienia to juz karna rozgrzewka. Ogółem miło spędzony czas', 'Anonymous', '2016-02-09 00:14', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.0, 'OK', 'WF jak to WF, typowy zapychacz, ale pan Zemankiewicz poprowadził kurs należycie. Na początku wprowadzenie do tematu, oprowadzenie po siłowni, potem głównie własne ćwiczenia - raz na jakiś czas mgr urozmaicał kurs swoimi ćwiczeniami. Możliwa jedna nieobecność i dwie, które można odrobić - nie robi problemu z odróbkami. Za jedną nieodrobioną nieobecność obniżył mi tylko pół oceny, także zachował się w porządku. Ocena wyjściowa 4.5 - za poprowadzenie jakiejś prostej rozgrzewki 5.0. Atmosfera na zajęciach miła, leci muzyczka, jak ktoś chce, to ćwiczy, jak ktoś nie chce, to może sobie przesiedzieć cały kurs schowany za maszynami na rowerku. Czasami puszczał trochę wcześniej, ale zajęcia prowadził do końca semestru. Profesjonalista w swoim fachu Polecam się zapisać, będę miło wspominać spędzone co tydzień popołudnie na zajęciach u tego pana.', 'Anonymous', '2016-06-06 20:14', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Narciarstwo', 5.5, 'Bardzo przyjemny kurs', 'Mega fajne zajęcia, każdego dnia najpierw trochę zajęć z doskonalenia techniki jazdy pod jego okiem, a potem już jazda wolna. Sympatyczny, rzeczowy prowadzący, który zna się na nartach. Polecam!', 'Anonymous', '2018-01-27 14:45', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.0, 'Polecam!', 'Świetnie poprowadzone zajęcia. Prowadzący nie traktuje studentów jak wyjadaczy siłowni i na start omawia wszystkie maszyny - dla początkujących jak znalazł. Część zajęć realizowana w stylu "wolnym" - każdy ćwiczy, co chce (przy czym prowadzący ma też zgrabną ściągę dla tych, którzy nie wiedzą, czym się zajęć), część zajęć jest przygotowana pod konkretny trening (kardio, siła itp). Na zaliczenie obecność (max jedna nieobecność i 4.5), żeby dostać 5.0 trzeba dodatkowo poprowadzić rozgrzewkę.', 'Anonymous', '2016-09-14 15:53', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 4.5, 'OK', 'Duża wiedza na temat tej dziedziny, porządne rozgrzewki z opisem słownym - co sięrozgrzewa, po co. W grze nie zawsze sędziuje, ale to wynika z tego, że studenci już sami wiedzą jak grać. Porządnie tłumaczy zasady gry itp. Wbrew pozorom unihokej to bardzo męczący sport - nie polecam, jak nie macie kondycji', 'Anonymous', '2016-11-27 09:56', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec towarzyski', 5.5, 'Polecam', 'Bardzo przyjemne zajęcia, do bardzo dobrej oceny wystarczy tylko obecność i przeprowadzenie jednej rozgrzewki, można poznać kilka tańców, może kiedyś się do czegoś przydadzą. Prowadzący z poczuciem humoru, można się czegoś nauczyć, zajęcia bezstresowe, miło i przyjemnie spędzony czas.', 'Anonymous', '2017-02-02 20:29', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Narciarstwo', 5.5, 'Bardzo przyjemny kurs', 'Mega fajne zajęcia, każdego dnia najpierw trochę zajęć z doskonalenia techniki jazdy pod jego okiem, a potem już jazda wolna. Sympatyczny, rzeczowy prowadzący, który zna się na nartach. Polecam!', 'Anonymous', '2018-01-27 14:45', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 4.0, 'Tak sobie', 'Prowadzący przekazuje zasady zaliczenia i się ich trzyma. Organizuje zajęcia i stara się pokazać różne techniki ćwiczeń. Jeżeli jednak ktoś ma plan skonstruowany przez trenera, to nie będzie mógł go realizować.', 'Anonymous', '2018-06-16 09:36', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.5, 'Świetny', 'Zajęcia są obowiązkowe, raz trzeba poprowadzić rozgrzewkę, nie toleruje on spóźnień. Nauczy każdego podstawowych tańców, jest bardzo cierpliwy i ma duże poczucie humoru. Serdecznie polecam', 'Anonymous', '2020-02-13 20:43', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, 'Fajniusio', 'Niestety przez wirusa nie było mi dane ukończyć kursu z tańca, jednakże na tych kilku zajęciach, na których byłam, bardzo polubiłam taniec oraz prowadzącego. Super bezstresowa atmosfera, ciekawe style tańca oraz humor to zdecydowanie trzy największe zalety tych zajęć!', 'Anonymous', '2020-09-15 18:03', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.5, 'Polecam te zajęcia', 'Pan Krzysztof jest baardzo sympatyczną osobą, bardzo lubi kontakt ze studentami. Posiada bardzo dużą wiedzę na temat zajęć, których prowadził. Zajęcia prowadzone były zdalnie na bardzo dobrym poziomie, zawsze dostawaliśmy rozpiskę całych zajęć, była część "teoretyczna" , a następnie ruchowa. I mimo zajęć zdalnych, po części ruchowej i tak można było się czasem dość zmęczyć, oczywiście w pozytywnym znaczeniu. Atmosfera na zajęciach jest super, prowadzący też, także polecam każdemu, który chce spróbować kulturystyki albo zapewnić sobie dodatkowy trening w swoim planie treningowym.', 'Anonymous', '2021-02-12 10:10', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka (zdalna)', 5.5, 'Kawał zdalnego wfu', 'Zajęcia miały regularny przebieg: po sprawdzeniu obecności uczestnicy dostawali na zoomie pdf z teorią dzisiejszych zajęć. Zawierała ona wstępne omówienie tematu (np. crossfit) oraz listę zadań. W ramach zajęć wykonywaliśmy zgodnie z instrukcjami Pana Krzysztofa większość ćwiczeń. Obecność na wszystkich zajęciach przy włączonej w trakcie ćwiczeń kamerze gwarantowała 4.0. Żeby uzyskać 5.0 należało poza zajęciami nagrać ostatnie ćwiczenie ze skryptu i przesłać nagranie pocztą. Dozwolona była jedna nieobecność, można było jednak nadrobić zajęcia w pewnym skończonym czasie, jeśli wcześniej skontaktowało się z Mgr Zemankiewiczem. Wtedy należało nagrać wszystkie ćwiczenia ze skryptu. Prowadzący odznaczał się humorem, był zaangażowany i zachęcał nas do ćwiczenia. W mojej opinii możliwość zaliczenia kursu bez żadnych przesyłanych nagrań, z możliwością zdobycia wyższej oceny za dodatkowe zwleczenie się z kanapy w weekend jest chyba najlepszym rozwiązaniem kwestii wfu w czasie pandemii. Poczułem się zachęcony do dbania o swoją formę mimo zamknięcia w czterech ścianach i zajęcia te oceniam nie tylko jako kolejny zaliczony kurs, ale przede wszystkim ważny i potrzebny element minionego semestru. Gorąco zachęcam wszystkich niezdecydowanych.', 'Anonymous', '2021-02-17 12:34', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka - obwód', 5.5, 'Przyjemny WF', 'Zajęcia w formie zdalnej odbywały się na włączonych kamerkach, prowadzący co tydzień przygotowywał listę z ćwiczeniami, a w połowie semestru zachęcał do układania sobie własnej listy. Dodatkowo czasem forma zajęć była inna, np. trzeba było ćwiczyć samodzielnie z pomocą aplikacji mobilnej. Prowadzący bardzo miły zawsze pomaga, gdy źle się wykonuje ćwiczenie i pochwali, gdy się poprawnie wykonuje.', 'Anonymous', '2021-09-16 11:10', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.5, 'MEGA', 'Super kurs do nauki podstaw, niestety zatańczyliśmy tylko 3 tańce przez zajęcia zdalne. Jednak widać, że prowadzący to wielki profesjonalista. Często wprowadza poprawia tancerzy, jednak jego rady są bardzo pomocne.', 'Anonymous', '2022-01-27 21:20', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Taniec', 5.0, 'Fajny kurs', 'Taniec jest przyjemnym wf-em, nauka tańca towarzyskiego od podstaw. Na zaliczenie przeprowadzenie 2 rozgrzewek do muzyki w trakcie semestru i obecności. Dopóki zajęcia odbywały się stacjonarnie były super, zdalnie jak każdy inny wf.', 'Anonymous', '2022-02-02 15:46', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Kulturystyka', 5.5, '5.0', 'Bardzo sympatyczny, miły człowiek. Na każdych zajęciach wykazuje się ogromną wiedzą na wszelkie tematy sportowe jak i kulturystyczne. Zna się na rzeczy. Daje dobre rady do wykonywanego właśnie ćwiczenia i uczy jak robić je poprawnie. Z zajęć można wynieść naprawdę dużo. Polecam', 'Waga opinii: x1,01', '2022-02-23 12:13', 6);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Unihokej', 5.0, 'Bardzo spoko', 'Uczy techniki, wymagający pod wzglądem wydolnościowym. Zaliczenie za obecności, w razie co zajęcia można odrobić z inną grupą.[/i][/code][/quote]', 'Anonymous', '2022-06-14 11:09', 6);


INSERT INTO teacher(category, full_name, academic_title, average_rating, details_link) VALUES('sportowcy', 'Żownir N', 'mgr', 4.75, 't,zownir-n-mgr,7481');
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Nauka pływania', 3.5, 'ocena opisowa - ogólnie nie najgorzej', 'Wszystko byłoby ok, gdyby nie fakt że na początku była mowa o ocenie na podstawie obecności (mogła być 1 usprawiedliwiona nieobecność na bdb). Na koniec wyszło zalicznie z pływania - ocena stylu - jak się pływa, stąd też nawet przy wszystkich obecnościach niełatwo było wyciągnąć 5 (dostałem 4, przy moim stylu nie najgorzej, ale szkoda, że nie wiedziałem od początku, że tak będzie to bym aż tak do chodzenia się nie zmuszał - nie to, że nie lubię a się zapisałem, bo lubię basen (choć z nauczeniem pływania mam problem ) ale czasem wiadomo, byłoby wolne, a jest basen, na który trzeba pójść. Poza tym zajęcia jak zajęcia, choć wydaje mi się, że lepiej mi szło jak byłem pod instruktażem pani Lisek.', 'Waga opinii: x1,26 opinia wyróżniona', '2009-06-15 14:22', 7);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Nauka pływania', 4.5, 'polecam', 'Polecam jeśli ktoś chce sie nauczyc pływac... wymaga sporo ale to dobrze', '', '2009-06-18 09:32', 7);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Nauka pływania', 5.5, 'plecam', 'Pani Żownir jasno przedstawiła czego bedzie wymagac i jak sie tylko wykonuje polecenia nie ma problemu z zaliczeniem nawet przy kilku nieobecnosciach mozna odrobic zajecia. Fakt jest test oceniajacy technike ale ja bez problemu z jedna nieobecnoscia mialem 5', 'Waga opinii: x1,01', '2009-06-19 18:38', 7);
INSERT INTO review(course_name, given_rating, title, review, reviewer, post_date, teacher_id) VALUES('Pływanie', 5.5, 'Polecam', 'Sposób prowadzenia zdecydowanie zależy od grupy, jaka się trafi. Raz zdarzyło mi się być w dość silnej grupie (wszyscy lepiej lub gorzej, ale radzili sobie z pływaniem) i wtedy mieliśmy naprawdę porządne treningi, a co jakiś czas bardzo przyjemne mecze piłki wodnej. Gdy innym razem była słaba grupa, to większość czasu spędzała na nauce pływania (mnóstwo ćwiczeń), a Ci którzy potrafili pływać, pływali zadym przez nią sposobem. Moim zdaniem bardzo miła kobieta. Nieobecności łatwo można odrobić i nietrudno uzyskać 5.', 'Waga opinii: x1,05', '2012-02-06 23:27', 7);


COMMIT;